name: lab_7_416488_test

on:
  push:
    branches:
      - dev-416488
    
jobs:
  test_dodawanie:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run test for dodawanie
        run: pytest calculator_test.py::test_dodawanie

  test_odejmowanie:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run test for odejmowanie
        run: pytest calculator_test.py::test_odejmowanie

  test_mnozenie:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run test for mnozenie
        run: pytest calculator_test.py::test_mnozenie

  test_dzielenie:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run test for dzielenie
        run: pytest calculator_test.py::test_dzielenie

  new_tests:
    runs-on: ubuntu-latest
    needs: [test_dodawanie, test_odejmowanie, test_mnozenie, test_dzielenie]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run new pandas tests
        run: |
          pytest calculator_test.py::test_create_dataframe
          pytest calculator_test.py::test_get_dataframe_shape